DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
`user_id` BIGINT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '用户ID',
`user_name` VARCHAR(16) NOT NULL  COMMENT '用户登录名',
`nick_name` VARCHAR(32) NOT NULL COMMENT '用户昵称',
`hashed_password` VARCHAR(128) NOT NULL COMMENT '用户密码，经过hash解析',
`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`created_by` VARCHAR(16) NOT NULL  COMMENT '创建人',
`updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`updated_by` VARCHAR(16) NOT NULL  COMMENT '更新人'
);